name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Build image
        run: docker build -t my-app .

deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - uses: actions/cache@v2
        with:
          path: ~/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/package-lock.json') }}

      - name: Login to Vercel
        uses: actions/docker/login@v2
        with:
          username: ${{ secrets.VERCEL_USERNAME }}
          password: ${{ secrets.VERCEL_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t vercel/my-app .
          docker push vercel/my-app

      - name: Upload to S3
        run: |
          docker run --rm -it -v $(pwd):/app -w /app lambci/lambda:build-python3.8 pip install awscli
          aws s3 cp ./my-app.zip s3://security-app-mai
