name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Build image
        run: docker build -t my-app .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Login to Vercel
        run: |
          echo ${{ secrets.VERCEL_TOKEN }} | docker login -u mesteves-baufestcom -p C4EFy9fnCqR3qRPczm0GRBkn registry.vercel.dev
      - name: Push image to Vercel
        run: docker push vercel/my-app
      - name: Upload to S3
        run: |
          docker run --rm -it -v $(pwd):/app -w /app lambci/lambda:build-python3.8 pip install awscli
          aws s3 cp ./my-app.zip s3://security-app-mai
