name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Build image
        run: docker build -t my-app .

  vercel_repository:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install vercel
        run: npm install -g vercel

      - name: Build for preview
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          vercel build --token=${{ secrets.VERCEL_TOKEN }}
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}

  deploy_s3:
    needs: vercel_repository
    runs-on: ubuntu-latest
        
    steps:
      - uses: actions/checkout@v2
      - name: Upload to S3
        run: |
          aws s3 cp ./my-app.zip s3://security-app-mai

    #   - name: Upload to S3
    #     run: |
    #       docker run --rm -it -v $(pwd):/app -w /app lambci/lambda:build-python3.8 pip install awscli
    #       aws s3 cp ./my-app.zip s3://security-app-mai

#   deploy_production:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v2
#       - name: Install vercel
#         run: npm install -g vercel

#       - name: Build for production
#         run: |
#           vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
#           vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
#           vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}